package xxnuc.oracle.apps.inv.billetissue.server;
// $Header: XXNUCBilletIssueAddItemVOImpl.java 120.000000000.25308 2018-03-30 19:01:08Z ankit.sharma noship $
import oracle.apps.fnd.framework.OAFwkConstants;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXNUCBilletIssueAddItemVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public XXNUCBilletIssueAddItemVOImpl() {
    }

    /**
     * Inititalizes VO
     */
    public void initQuery() {
        if (this.isLoggingEnabled(OAFwkConstants.STATEMENT))
            this.writeDiagnostics(this, 
                                  "XXNUCBilletIssueAddItemVOImpl: initQuery", 
                                  OAFwkConstants.STATEMENT);
//        System.out.println("VO initQuery entry");
        this.setWhereClause(null);
        this.setWhereClauseParams(null);
        this.clearCache();
        this.executeQuery();
//        System.out.println("VO initQuery exit");
    }
}
