package xxnuc.oracle.apps.inv.billetissue.server;
// $Header: XXNUCBilletIssueAddItemVORowImpl.java 120.000000000.25308 2018-03-30 19:01:08Z ankit.sharma noship $
import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXNUCBilletIssueAddItemVORowImpl extends OAViewRowImpl {
    public static final int BATCHID = 0;
    public static final int BATCHSTEPNO = 1;
    public static final int ISSUEQTY = 2;
    public static final int ITEMID = 3;
    public static final int SEGMENT1 = 4;
    public static final int ORGID = 5;
    public static final int OPRNNO = 6;
    public static final int LOCATORID = 7;
    public static final int SUBINVCODE = 8;
    public static final int UOM = 9;
    public static final int LOTNO = 10;
    public static final int BATCHNO = 11;
    public static final int ORGCODE = 12;
    public static final int LOCATORNUM = 13;
    public static final int ACTUALQTY = 14;
    public static final int DESCRIPTION = 15;
    public static final int SECUOM = 16;
    public static final int SUMQTY = 17;
    public static final int ADD = 18;
    public static final int DEL = 19;
    public static final int DETAILVIEW = 20;
    public static final int CONTRIBUTETOYIELD = 21;

    /**This is the default constructor (do not remove)
     */
    public XXNUCBilletIssueAddItemVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute BatchId
     */
    public String getBatchId() {
        return (String) getAttributeInternal(BATCHID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BatchId
     */
    public void setBatchId(String value) {
        setAttributeInternal(BATCHID, value);
    }

    /**Gets the attribute value for the calculated attribute BatchstepNo
     */
    public String getBatchstepNo() {
        return (String) getAttributeInternal(BATCHSTEPNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BatchstepNo
     */
    public void setBatchstepNo(String value) {
        setAttributeInternal(BATCHSTEPNO, value);
    }

    /**Gets the attribute value for the calculated attribute IssueQty
     */
    public String getIssueQty() {
        return (String) getAttributeInternal(ISSUEQTY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IssueQty
     */
    public void setIssueQty(String value) {
        setAttributeInternal(ISSUEQTY, value);
    }

    /**Gets the attribute value for the calculated attribute ItemId
     */
    public String getItemId() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemId
     */
    public void setItemId(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**Gets the attribute value for the calculated attribute Segment1
     */
    public String getSegment1() {
        return (String) getAttributeInternal(SEGMENT1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Segment1
     */
    public void setSegment1(String value) {
        setAttributeInternal(SEGMENT1, value);
    }

    /**Gets the attribute value for the calculated attribute OrgId
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgId
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for the calculated attribute OprnNo
     */
    public String getOprnNo() {
        return (String) getAttributeInternal(OPRNNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OprnNo
     */
    public void setOprnNo(String value) {
        setAttributeInternal(OPRNNO, value);
    }

    /**Gets the attribute value for the calculated attribute LocatorId
     */
    public String getLocatorId() {
        return (String) getAttributeInternal(LOCATORID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LocatorId
     */
    public void setLocatorId(String value) {
        setAttributeInternal(LOCATORID, value);
    }

    /**Gets the attribute value for the calculated attribute SubinvCode
     */
    public String getSubinvCode() {
        return (String) getAttributeInternal(SUBINVCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SubinvCode
     */
    public void setSubinvCode(String value) {
        setAttributeInternal(SUBINVCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Uom
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**Gets the attribute value for the calculated attribute LotNo
     */
    public String getLotNo() {
        return (String) getAttributeInternal(LOTNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LotNo
     */
    public void setLotNo(String value) {
        setAttributeInternal(LOTNO, value);
    }

    /**Gets the attribute value for the calculated attribute BatchNo
     */
    public String getBatchNo() {
        return (String) getAttributeInternal(BATCHNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BatchNo
     */
    public void setBatchNo(String value) {
        setAttributeInternal(BATCHNO, value);
    }

    /**Gets the attribute value for the calculated attribute OrgCode
     */
    public String getOrgCode() {
        return (String) getAttributeInternal(ORGCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgCode
     */
    public void setOrgCode(String value) {
        setAttributeInternal(ORGCODE, value);
    }

    /**Gets the attribute value for the calculated attribute LocatorNum
     */
    public String getLocatorNum() {
        return (String) getAttributeInternal(LOCATORNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LocatorNum
     */
    public void setLocatorNum(String value) {
        setAttributeInternal(LOCATORNUM, value);
    }

    /**Gets the attribute value for the calculated attribute ActualQty
     */
    public String getActualQty() {
        return (String) getAttributeInternal(ACTUALQTY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ActualQty
     */
    public void setActualQty(String value) {
        setAttributeInternal(ACTUALQTY, value);
    }

    /**Gets the attribute value for the calculated attribute Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute Secuom
     */
    public String getSecuom() {
        return (String) getAttributeInternal(SECUOM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Secuom
     */
    public void setSecuom(String value) {
        setAttributeInternal(SECUOM, value);
    }

    /**Gets the attribute value for the calculated attribute Sumqty
     */
    public String getSumqty() {
        return (String) getAttributeInternal(SUMQTY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sumqty
     */
    public void setSumqty(String value) {
        setAttributeInternal(SUMQTY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BATCHID:
            return getBatchId();
        case BATCHSTEPNO:
            return getBatchstepNo();
        case ISSUEQTY:
            return getIssueQty();
        case ITEMID:
            return getItemId();
        case SEGMENT1:
            return getSegment1();
        case ORGID:
            return getOrgId();
        case OPRNNO:
            return getOprnNo();
        case LOCATORID:
            return getLocatorId();
        case SUBINVCODE:
            return getSubinvCode();
        case UOM:
            return getUom();
        case LOTNO:
            return getLotNo();
        case BATCHNO:
            return getBatchNo();
        case ORGCODE:
            return getOrgCode();
        case LOCATORNUM:
            return getLocatorNum();
        case ACTUALQTY:
            return getActualQty();
        case DESCRIPTION:
            return getDescription();
        case SECUOM:
            return getSecuom();
        case SUMQTY:
            return getSumqty();
        case ADD:
            return getAdd();
        case DEL:
            return getDel();
        case DETAILVIEW:
            return getDetailView();
        case CONTRIBUTETOYIELD:
            return getContributeToYield();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BATCHID:
            setBatchId((String)value);
            return;
        case BATCHSTEPNO:
            setBatchstepNo((String)value);
            return;
        case ISSUEQTY:
            setIssueQty((String)value);
            return;
        case ITEMID:
            setItemId((String)value);
            return;
        case SEGMENT1:
            setSegment1((String)value);
            return;
        case ORGID:
            setOrgId((String)value);
            return;
        case OPRNNO:
            setOprnNo((String)value);
            return;
        case LOCATORID:
            setLocatorId((String)value);
            return;
        case SUBINVCODE:
            setSubinvCode((String)value);
            return;
        case UOM:
            setUom((String)value);
            return;
        case LOTNO:
            setLotNo((String)value);
            return;
        case BATCHNO:
            setBatchNo((String)value);
            return;
        case ORGCODE:
            setOrgCode((String)value);
            return;
        case LOCATORNUM:
            setLocatorNum((String)value);
            return;
        case ACTUALQTY:
            setActualQty((String)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case SECUOM:
            setSecuom((String)value);
            return;
        case SUMQTY:
            setSumqty((String)value);
            return;
        case ADD:
            setAdd((String)value);
            return;
        case DEL:
            setDel((String)value);
            return;
        case DETAILVIEW:
            setDetailView((Boolean)value);
            return;
        case CONTRIBUTETOYIELD:
            setContributeToYield((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Add
     */
    public String getAdd() {
        return (String) getAttributeInternal(ADD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Add
     */
    public void setAdd(String value) {
        setAttributeInternal(ADD, value);
    }

    /**Gets the attribute value for the calculated attribute Del
     */
    public String getDel() {
        return (String) getAttributeInternal(DEL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Del
     */
    public void setDel(String value) {
        setAttributeInternal(DEL, value);
    }


    /**Gets the attribute value for the calculated attribute DetailView
     */
    public Boolean getDetailView() {
        return (Boolean) getAttributeInternal(DETAILVIEW);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DetailView
     */
    public void setDetailView(Boolean value) {
        setAttributeInternal(DETAILVIEW, value);
    }

    /**Gets the attribute value for the calculated attribute ContributeToYield
     */
    public String getContributeToYield() {
        return (String) getAttributeInternal(CONTRIBUTETOYIELD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ContributeToYield
     */
    public void setContributeToYield(String value) {
        setAttributeInternal(CONTRIBUTETOYIELD, value);
    }
}
